---
output: 
  html_document:
    df_print: paged
    self_contained: TRUE
    css: report.css
params:
  df_diff: NULL
  use_plotly: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE,
                      rownames.print = FALSE, rows.print = 10,
                      fig.height = 6, fig.width = 9)
knitr::knit_hooks$set(width=local({
    .width <- 0
    function(before, options, envir) {
        if (before) .width <<- options(width=options$width)
        else options(.width)
    }
}))
library(different)
```

```{r diff-from-params, include = FALSE}
stopifnot(!is.null(df_diff))
df_diff <- params$df_diff
```

# Differences Report {.tabset}

## Summary


<details><summary>Dimensions</summary>
```{r summary-dimensions}
purrr::map_dfr(setNames(z$meta$dims, z$meta$names),
    ~ dplyr::data_frame(Rows = .[1], Columns = .[2]), .id = "Data Set") %>% 
  knitr::kable()
```

</details>


<details>
<summary>Columns</summary>

```{r summary-columns}
purrr::map2(
  df_diff$meta$colnames, 
  df_diff$meta$coltypes, 
  ~ dplyr::data_frame(Column = .x, Type = .y)
) %>% 
  purrr::reduce(
    full_join, 
    suffix = paste("", c(df_diff$meta$names[1], df_diff$meta$names[2])),
    by = "Column"
  ) %>% 
  {
    .x <- .
    type_var <- paste("Type", df_diff$meta$names[2])
    if (type_var %in% names(.x)) {
      type_var_y <- rlang::sym(type_var)
      type_var_x <- rlang::sym(paste("Type", df_diff$meta$names[1]))
      dplyr::mutate(
        .x, 
        !!type_var_y := ifelse(!is.na(!!type_var_y) & !is.na(!!type_var_x) & !!type_var_y != !!type_var_x, 
                               paste0('<span style="color: red">', !!type_var_y, "</span>"), 
                               !!type_var_y))
    } else .x
  } %>% 
  dplyr::mutate_at(
    dplyr::vars(dplyr::starts_with("Type")),
    function(x) ifelse(is.na(x), "\U274C", x)
  ) %>% 
  knitr::kable(escape = FALSE)
```

</details>

<details>
<summary>Differences Summary</summary>

```{r summary-diff}
df_diff$diff %>% 
  dplyr::select(-misses) %>% 
  dplyr::mutate(
    state = dplyr::case_when(
      stringr::str_detect(state, "unique_x") ~ paste("unique", df_diff$meta$names[1]),
      stringr::str_detect(state, "unique_y") ~ paste("unique", df_diff$meta$names[2]),
      TRUE ~ state
    ),
    miss_count = ifelse(is.na(miss_count), "", paste(miss_count))
  ) %>% 
  knitr::kable(
    col.names = c("Column", "Difference", "Number of Differences")
  )
```

</details>

## Visualization

```{r visualization, out.width="100%"}
if (params$use_plotly && requireNamespace("plotly", quietly = TRUE)) {
  plotly::ggplotly(plot(df_diff))
} else {
  plot(df_diff)
}
```

## Differences by Column {.tabset .tabset-fade .tabset-pills}

```{r diffs-by-column, include=FALSE}
out <- vector(mode = "character", length = length(df_diff$tidy))
for (colname in names(df_diff$tidy)) {
  out[[colname]] <- knitr::knit_expand(
    text = c(
      "### {{colname}}",
      "```{r, echo = FALSE}",
      "x <- df_diff$tidy[['{{colname}}']]",
      "colnames(x)[2:3] <- df_diff$meta$names",
      "x",
      "```")
  )
}
```

`r paste(knitr::knit(text = out), collapse = "\n")`
